spring.application.name=RescueNet-Backend

# Server Configuration
server.port=8089

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/rescuenet_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT Properties
jwt.secret=ThisIsMyVerySecretKeyForRescueNetProject123456789
jwt.expiration=86400000

# OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html